version: "3"
services:
    mysql:
        image: mysql:5.7
        restart: "always"
        environment:
            - MYSQL_USER=hoge
            - MYSQL_PASSWORD=hoge
            - MYSQL_DATABASE=hoge
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - "./volumes/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    python:
        image: python:3
        restart: "no"
        environment:
            - MYSQL_USER=hoge
            - MYSQL_PASSWORD=hoge
            - MYSQL_DATABASE=hoge
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        links:
            - mysql:db
        working_dir: /app
        volumes:
            - "./requirements.txt:/app/requirements.txt:ro"
            - "./src:/app/src:ro"
            - "./config:/app/config:ro"

