version: "3"
services:
    mysql:
        image: mysql:5.7
        restart: "always"
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - "./volumes/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: "no"
        environment:
            - PYTHONPATH=src/main/python
        links:
            - mysql:db
        volumes:
            - "./requirements.txt:/app/requirements.txt:ro"
            - "./tasks.py:/app/tasks.py:ro"
            - "./src:/app/src:ro"
            - "./config:/app/config:ro"
            - "./tmp:/app/tmp"

