- host: db
  database: product
  user: product-user
  password:
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
- host: db
  database: marketing
  user: marketing-user
  password:
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

